name: Logger CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create log file
        run: echo "Pipeline executed successfully" > log.txt

      - name: Validate check if file exists
        run: |
          if [ ! -f log.txt ]; then
            echo "log.txt does not exists!"
            exit 1
          fi

      - name: Check file not empty
        run: |
          if [ ! -s log.txt ]; then
            echo "log.txt is empty!"
          fi

      - name: Check expected content
        run: |
          if ! grep -q "Pipeline executed successfully" log.txt; then
            echo "Expected message not found!"
            exit 1
           fi 

      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: log.txt
