name: Logger CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EXPECTED_MESSAGE: "Pipeline executed successfully"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create log file
        run: echo "Pipeline executed successfully" > log.txt
        run: echo "Expected message: $EXPECTED_MESSAGE"
        
      - name: Make validation script executable
        run: chmod +x validate.sh

      - name: Run validation script
        run: ./validate.sh

      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: log.txt
