name: Run Process Logger

on:
  push:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x process_logger.sh

      - name: Run script
        run: ./process_logger.sh
